### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by tafia**
fix issues appeared in [discussion](https://github.com/PistonDevelopers/imageproc/issues/97#issuecomment-170557464)

### CODE REVIEW

**Comment by tafia** [comment]
Kept 2 levels only for versions. I hope crate owners will upgrade at least 2nd level if there is a breaking change.

**Comment by bvssvni** [comment]
The "z" part in "x.y.z" is interpreted by Cargo as the minimum version. Change in the first non-zero number counts as a breaking change. When bumping the first non-zero number in any dependency it is a good idea to bump the first non-zero number in the library, to avoid breaking existing code.

**Comment by bvssvni** [comment]
You can set "image" to 0.6.1 to get the bug fixes and bump "imageproc" to 0.2.0.

**Comment by theotherphil** [comment]
Thanks both for looking into this. I won't have time to do anything tonight, but I'm happy for whatever version changes @bvssvni suggests. I'll fix on the weekend if it's not already done by then.

**Comment by bvssvni** [comment]
Opened https://github.com/PistonDevelopers/imageproc/pull/104. Closing this.

**Pull request closed without merging**
