### PR TITLE
Bump dependency Versions

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
This just updates various dependencies to their latest version. No changes were needed and all tests should still pass.

### CODE REVIEW

**Comment by theotherphil** [comment]
Happy to merge, but is there a specific reason for this bump?

**Comment by Michael-F-Bryan** [comment]
I'm working on a fairly large project at work and noticed that a lot of compilation time is wasted recompiling different versions of the same crate. A full release build will typically take 5-10 minutes, so I was hoping to decrease compilation times a bit by upgrading people's dependencies. 

In particular I believe `imageproc` currently uses older versions of `rayon` and `nalgebra`. With `nalgebra` pulling in compilation heavy things like `typenum`.

**Comment by theotherphil** [comment]
Ah, right. Thanks.

**Comment by theotherphil** [comment]
There's an open ticket for getting rid of the nalgebra dependency altogether, as we use almost nothing from it.

**Pull request merged**
